name: Water meter OCR from image
description: "Put a webcam in front of your utility meter, save the output to an image and let AWS Rekognition push the reading over mqtt"
version: "0.0.1"
slug: "water_meter_ocr_from_image"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  upd_interval: 1800
  user: null
  password: null
  nas_ip: "192.168.178.111"
  baseline: 1
  under: 1
  over: 1
  crop_region: "320,240,570,300" # left top right bottom
  aws_access_key_id: null
  aws_secret_access_key: null
  mqtt_host: 127.0.0.1
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_pwd: "mqtt_pwd"
  mqtt_topic: "home/meter"
schema:
  upd_interval: int
  user: str
  password: str
  nas_ip: str
  baseline: int
  under: int
  over: int
  crop_region: str?
  aws_access_key_id: str
  aws_secret_access_key: str
  region: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pwd: str
  mqtt_topic: str